corpusPath: "../grobid-astro/resources/dataset/astro/corpus"
templatePath: "../grobid-astro/resources/dataset/astro/crfpp-templates/astro.template"
grobidHome: "../grobid-home"

model:
  name: "astro"
  engine: "wapiti"
  #engine: "delft"
  wapiti:
    # wapiti training parameters, they will be used at training time only
    epsilon: 0.00001
    window: 20
    nbMaxIterations: 2000
  delft:
    # deep learning parameters
    architecture: "BidLSTM_CRF"
    #architecture: "scibert"
    useELMo: false
    embeddings_name: "glove-840B"
